name: build-container
on:
  pull_request:
    branches:
      - master
      - main
  repository_dispatch:
  push:
    branches:
      - master


jobs:
  build_container:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: login to dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: build container
        uses: docker/build-push-action@v2
        with:
          context: Blitz.Web
          tags: abdusco/blitz:latest
          load: true

      - name: push
        run: docker push abdusco/blitz:latest